[build]
jobs = 8
rustc-wrapper = "sccache"

[env]
SCCACHE_CACHE_SIZE = "10G"
SCCACHE_DIR = "/Users/tfarrell/.cache/sccache"
RUSTC_WRAPPER = "sccache"

FFMPEG_PKG_CONFIG_PATH = "NONE"
LIBAVCODEC_NO_PKG_CONFIG = "1"
LIBAVDEVICE_NO_PKG_CONFIG = "1"
LIBAVFILTER_NO_PKG_CONFIG = "1"
LIBAVFORMAT_NO_PKG_CONFIG = "1"
LIBAVRESAMPLE_NO_PKG_CONFIG = "1"
LIBAVUTIL_NO_PKG_CONFIG = "1"
LIBPOSTPROC_NO_PKG_CONFIG = "1"
LIBSWRESAMPLE_NO_PKG_CONFIG = "1"
LIBSWSCALE_NO_PKG_CONFIG = "1"
FFMPEG_INCLUDE_DIR = { value = "/Users/tfarrell/Documents/CODE/SMDB_Companion/src-tauri/resources/ffmpeg/universal/include", relative = false }


[profile.dev]
incremental = true
debug = 1
opt-level = 1
