[build]
jobs = 8
rustc-wrapper = "sccache"

[env]
SCCACHE_CACHE_SIZE = "10G"
SCCACHE_DIR = "/Users/tfarrell/.cache/sccache"
RUSTC_WRAPPER = "sccache"

[profile.dev]
incremental = true
debug = 1          # Reduced debug info for faster builds
opt-level = 1      # Slight optimization without impacting compile time much
