pub use crate::duplicates::*;
pub use crate::find_replace::FindPanel;
pub use crate::ui::*;
pub use crate::*;
pub use anyhow::Result;
pub use dirs::home_dir;
pub use eframe::egui::{self, RichText, Ui};
pub use rayon::prelude::*;
pub use rfd::FileDialog;
pub use serde::Deserialize;
pub use sqlx::sqlite::SqliteRow;
pub use sqlx::{sqlite::SqlitePool, Row};
pub use std::collections::{HashMap, HashSet};
pub use std::fs::{self};
pub use std::hash::Hash;
pub use std::path::Path;
pub use std::sync::{Mutex, RwLock};
pub use tokio::sync::mpsc;

pub const TABLE: &str = "justinmetadata";
pub use crate::duplicates::order::OrderOperator as O;
pub use crate::duplicates::Algorithm as A;
