name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "x86_64-apple-darwin"
          - platform: "windows-latest"
            args: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        run: npm install -g pnpm

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install Rust target
        run: rustup target add ${{ matrix.args }}

      - name: install Tauri CLI
        run: cargo install tauri-cli

      - name: install frontend dependencies
        run: pnpm install

      - name: build Tauri app
        run: cargo tauri build --target ${{ matrix.args }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
